// This file is auto-generated by @hey-api/openapi-ts

export const ActivityMessageSchema = {
    properties: {
        id: {
            type: 'string',
            title: 'Id'
        },
        role: {
            type: 'string',
            const: 'activity',
            title: 'Role',
            default: 'activity'
        },
        activityType: {
            type: 'string',
            title: 'Activitytype'
        },
        content: {
            additionalProperties: true,
            type: 'object',
            title: 'Content'
        }
    },
    additionalProperties: true,
    type: 'object',
    required: ['id', 'activityType', 'content'],
    title: 'ActivityMessage',
    description: 'An activity progress message emitted between chat messages.'
} as const;

export const AgentStateRequestSchema = {
    properties: {
        threadId: {
            type: 'string',
            title: 'Threadid'
        },
        appName: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Appname'
        },
        userId: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Userid'
        },
        name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        properties: {
            anyOf: [
                {},
                {
                    type: 'null'
                }
            ],
            title: 'Properties'
        }
    },
    type: 'object',
    required: ['threadId'],
    title: 'AgentStateRequest',
    description: `Request body for /agents/state endpoint.

EXPERIMENTAL: This endpoint is subject to change in future versions.`
} as const;

export const AssistantMessageSchema = {
    properties: {
        id: {
            type: 'string',
            title: 'Id'
        },
        role: {
            type: 'string',
            const: 'assistant',
            title: 'Role',
            default: 'assistant'
        },
        content: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Content'
        },
        name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        toolCalls: {
            anyOf: [
                {
                    items: {
                        '$ref': '#/components/schemas/ToolCall'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Toolcalls'
        }
    },
    additionalProperties: true,
    type: 'object',
    required: ['id'],
    title: 'AssistantMessage',
    description: 'An assistant message.'
} as const;

export const BinaryInputContentSchema = {
    properties: {
        type: {
            type: 'string',
            const: 'binary',
            title: 'Type',
            default: 'binary'
        },
        mimeType: {
            type: 'string',
            title: 'Mimetype'
        },
        id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Id'
        },
        url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Url'
        },
        data: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Data'
        },
        filename: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Filename'
        }
    },
    additionalProperties: true,
    type: 'object',
    required: ['mimeType'],
    title: 'BinaryInputContent',
    description: 'A binary payload reference in a multimodal user message.'
} as const;

export const Body_login_login_access_tokenSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^password$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            format: 'password',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            format: 'password',
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_login-login_access_token'
} as const;

export const ContextSchema = {
    properties: {
        description: {
            type: 'string',
            title: 'Description'
        },
        value: {
            type: 'string',
            title: 'Value'
        }
    },
    additionalProperties: true,
    type: 'object',
    required: ['description', 'value'],
    title: 'Context',
    description: 'Additional context for the agent.'
} as const;

export const DeveloperMessageSchema = {
    properties: {
        id: {
            type: 'string',
            title: 'Id'
        },
        role: {
            type: 'string',
            const: 'developer',
            title: 'Role',
            default: 'developer'
        },
        content: {
            type: 'string',
            title: 'Content'
        },
        name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        }
    },
    additionalProperties: true,
    type: 'object',
    required: ['id', 'content'],
    title: 'DeveloperMessage',
    description: 'A developer message.'
} as const;

export const FunctionCallSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        },
        arguments: {
            type: 'string',
            title: 'Arguments'
        }
    },
    additionalProperties: true,
    type: 'object',
    required: ['name', 'arguments'],
    title: 'FunctionCall',
    description: 'Name and arguments of a function call.'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const ItemCreateSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    required: ['title'],
    title: 'ItemCreate'
} as const;

export const ItemPublicSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['title', 'id', 'owner_id'],
    title: 'ItemPublic'
} as const;

export const ItemUpdateSchema = {
    properties: {
        title: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    title: 'ItemUpdate'
} as const;

export const ItemsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ItemPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ItemsPublic'
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message'
} as const;

export const NewPasswordSchema = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['token', 'new_password'],
    title: 'NewPassword'
} as const;

export const PrivateUserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            title: 'Email'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        full_name: {
            type: 'string',
            title: 'Full Name'
        },
        is_verified: {
            type: 'boolean',
            title: 'Is Verified',
            default: false
        }
    },
    type: 'object',
    required: ['email', 'password', 'full_name'],
    title: 'PrivateUserCreate'
} as const;

export const RunAgentInputSchema = {
    properties: {
        threadId: {
            type: 'string',
            title: 'Threadid'
        },
        runId: {
            type: 'string',
            title: 'Runid'
        },
        parentRunId: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Parentrunid'
        },
        state: {
            title: 'State'
        },
        messages: {
            items: {
                oneOf: [
                    {
                        '$ref': '#/components/schemas/DeveloperMessage'
                    },
                    {
                        '$ref': '#/components/schemas/SystemMessage'
                    },
                    {
                        '$ref': '#/components/schemas/AssistantMessage'
                    },
                    {
                        '$ref': '#/components/schemas/UserMessage'
                    },
                    {
                        '$ref': '#/components/schemas/ToolMessage'
                    },
                    {
                        '$ref': '#/components/schemas/ActivityMessage'
                    }
                ],
                discriminator: {
                    propertyName: 'role',
                    mapping: {
                        activity: '#/components/schemas/ActivityMessage',
                        assistant: '#/components/schemas/AssistantMessage',
                        developer: '#/components/schemas/DeveloperMessage',
                        system: '#/components/schemas/SystemMessage',
                        tool: '#/components/schemas/ToolMessage',
                        user: '#/components/schemas/UserMessage'
                    }
                }
            },
            type: 'array',
            title: 'Messages'
        },
        tools: {
            items: {
                '$ref': '#/components/schemas/Tool'
            },
            type: 'array',
            title: 'Tools'
        },
        context: {
            items: {
                '$ref': '#/components/schemas/Context'
            },
            type: 'array',
            title: 'Context'
        },
        forwardedProps: {
            title: 'Forwardedprops'
        }
    },
    additionalProperties: true,
    type: 'object',
    required: ['threadId', 'runId', 'state', 'messages', 'tools', 'context', 'forwardedProps'],
    title: 'RunAgentInput',
    description: 'Input for running an agent.'
} as const;

export const SystemMessageSchema = {
    properties: {
        id: {
            type: 'string',
            title: 'Id'
        },
        role: {
            type: 'string',
            const: 'system',
            title: 'Role',
            default: 'system'
        },
        content: {
            type: 'string',
            title: 'Content'
        },
        name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        }
    },
    additionalProperties: true,
    type: 'object',
    required: ['id', 'content'],
    title: 'SystemMessage',
    description: 'A system message.'
} as const;

export const TextInputContentSchema = {
    properties: {
        type: {
            type: 'string',
            const: 'text',
            title: 'Type',
            default: 'text'
        },
        text: {
            type: 'string',
            title: 'Text'
        }
    },
    additionalProperties: true,
    type: 'object',
    required: ['text'],
    title: 'TextInputContent',
    description: 'A text fragment in a multimodal user message.'
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: ['access_token'],
    title: 'Token'
} as const;

export const ToolSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        },
        description: {
            type: 'string',
            title: 'Description'
        },
        parameters: {
            title: 'Parameters'
        }
    },
    additionalProperties: true,
    type: 'object',
    required: ['name', 'description', 'parameters'],
    title: 'Tool',
    description: 'A tool definition.'
} as const;

export const ToolCallSchema = {
    properties: {
        id: {
            type: 'string',
            title: 'Id'
        },
        type: {
            type: 'string',
            const: 'function',
            title: 'Type',
            default: 'function'
        },
        function: {
            '$ref': '#/components/schemas/FunctionCall'
        }
    },
    additionalProperties: true,
    type: 'object',
    required: ['id', 'function'],
    title: 'ToolCall',
    description: 'A tool call, modelled after OpenAI tool calls.'
} as const;

export const ToolMessageSchema = {
    properties: {
        id: {
            type: 'string',
            title: 'Id'
        },
        role: {
            type: 'string',
            const: 'tool',
            title: 'Role',
            default: 'tool'
        },
        content: {
            type: 'string',
            title: 'Content'
        },
        toolCallId: {
            type: 'string',
            title: 'Toolcallid'
        },
        error: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Error'
        }
    },
    additionalProperties: true,
    type: 'object',
    required: ['id', 'content', 'toolCallId'],
    title: 'ToolMessage',
    description: 'A tool result message.'
} as const;

export const UpdatePasswordSchema = {
    properties: {
        current_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Current Password'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['current_password', 'new_password'],
    title: 'UpdatePassword'
} as const;

export const UserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserCreate'
} as const;

export const UserMessageSchema = {
    properties: {
        id: {
            type: 'string',
            title: 'Id'
        },
        role: {
            type: 'string',
            const: 'user',
            title: 'Role',
            default: 'user'
        },
        content: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    items: {
                        oneOf: [
                            {
                                '$ref': '#/components/schemas/TextInputContent'
                            },
                            {
                                '$ref': '#/components/schemas/BinaryInputContent'
                            }
                        ],
                        discriminator: {
                            propertyName: 'type',
                            mapping: {
                                binary: '#/components/schemas/BinaryInputContent',
                                text: '#/components/schemas/TextInputContent'
                            }
                        }
                    },
                    type: 'array'
                }
            ],
            title: 'Content'
        },
        name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        }
    },
    additionalProperties: true,
    type: 'object',
    required: ['id', 'content'],
    title: 'UserMessage',
    description: 'A user message supporting text or multimodal content.'
} as const;

export const UserPublicSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['email', 'id'],
    title: 'UserPublic'
} as const;

export const UserRegisterSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserRegister'
} as const;

export const UserUpdateSchema = {
    properties: {
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 128,
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        }
    },
    type: 'object',
    title: 'UserUpdate'
} as const;

export const UserUpdateMeSchema = {
    properties: {
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        }
    },
    type: 'object',
    title: 'UserUpdateMe'
} as const;

export const UsersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/UserPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'UsersPublic'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;