// This file is auto-generated by @hey-api/openapi-ts

export const ActivityMessageSchema = {
    properties: {
        id: {
            type: 'string',
            title: 'Id'
        },
        role: {
            type: 'string',
            const: 'activity',
            title: 'Role',
            default: 'activity'
        },
        activityType: {
            type: 'string',
            title: 'Activitytype'
        },
        content: {
            additionalProperties: true,
            type: 'object',
            title: 'Content'
        }
    },
    additionalProperties: true,
    type: 'object',
    required: ['id', 'activityType', 'content'],
    title: 'ActivityMessage',
    description: 'An activity progress message emitted between chat messages.'
} as const;

export const AgentStateRequestSchema = {
    properties: {
        threadId: {
            type: 'string',
            title: 'Threadid'
        },
        appName: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Appname'
        },
        userId: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Userid'
        },
        name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        properties: {
            anyOf: [
                {},
                {
                    type: 'null'
                }
            ],
            title: 'Properties'
        }
    },
    type: 'object',
    required: ['threadId'],
    title: 'AgentStateRequest',
    description: `Request body for /agents/state endpoint.

EXPERIMENTAL: This endpoint is subject to change in future versions.`
} as const;

export const AssistantMessageSchema = {
    properties: {
        id: {
            type: 'string',
            title: 'Id'
        },
        role: {
            type: 'string',
            const: 'assistant',
            title: 'Role',
            default: 'assistant'
        },
        content: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Content'
        },
        name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        toolCalls: {
            anyOf: [
                {
                    items: {
                        '$ref': '#/components/schemas/ToolCall'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Toolcalls'
        }
    },
    additionalProperties: true,
    type: 'object',
    required: ['id'],
    title: 'AssistantMessage',
    description: 'An assistant message.'
} as const;

export const BinaryInputContentSchema = {
    properties: {
        type: {
            type: 'string',
            const: 'binary',
            title: 'Type',
            default: 'binary'
        },
        mimeType: {
            type: 'string',
            title: 'Mimetype'
        },
        id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Id'
        },
        url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Url'
        },
        data: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Data'
        },
        filename: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Filename'
        }
    },
    additionalProperties: true,
    type: 'object',
    required: ['mimeType'],
    title: 'BinaryInputContent',
    description: 'A binary payload reference in a multimodal user message.'
} as const;

export const ContextSchema = {
    properties: {
        description: {
            type: 'string',
            title: 'Description'
        },
        value: {
            type: 'string',
            title: 'Value'
        }
    },
    additionalProperties: true,
    type: 'object',
    required: ['description', 'value'],
    title: 'Context',
    description: 'Additional context for the agent.'
} as const;

export const DeveloperMessageSchema = {
    properties: {
        id: {
            type: 'string',
            title: 'Id'
        },
        role: {
            type: 'string',
            const: 'developer',
            title: 'Role',
            default: 'developer'
        },
        content: {
            type: 'string',
            title: 'Content'
        },
        name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        }
    },
    additionalProperties: true,
    type: 'object',
    required: ['id', 'content'],
    title: 'DeveloperMessage',
    description: 'A developer message.'
} as const;

export const FunctionCallSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        },
        arguments: {
            type: 'string',
            title: 'Arguments'
        }
    },
    additionalProperties: true,
    type: 'object',
    required: ['name', 'arguments'],
    title: 'FunctionCall',
    description: 'Name and arguments of a function call.'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const RunAgentInputSchema = {
    properties: {
        threadId: {
            type: 'string',
            title: 'Threadid'
        },
        runId: {
            type: 'string',
            title: 'Runid'
        },
        parentRunId: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Parentrunid'
        },
        state: {
            title: 'State'
        },
        messages: {
            items: {
                oneOf: [
                    {
                        '$ref': '#/components/schemas/DeveloperMessage'
                    },
                    {
                        '$ref': '#/components/schemas/SystemMessage'
                    },
                    {
                        '$ref': '#/components/schemas/AssistantMessage'
                    },
                    {
                        '$ref': '#/components/schemas/UserMessage'
                    },
                    {
                        '$ref': '#/components/schemas/ToolMessage'
                    },
                    {
                        '$ref': '#/components/schemas/ActivityMessage'
                    }
                ],
                discriminator: {
                    propertyName: 'role',
                    mapping: {
                        activity: '#/components/schemas/ActivityMessage',
                        assistant: '#/components/schemas/AssistantMessage',
                        developer: '#/components/schemas/DeveloperMessage',
                        system: '#/components/schemas/SystemMessage',
                        tool: '#/components/schemas/ToolMessage',
                        user: '#/components/schemas/UserMessage'
                    }
                }
            },
            type: 'array',
            title: 'Messages'
        },
        tools: {
            items: {
                '$ref': '#/components/schemas/Tool'
            },
            type: 'array',
            title: 'Tools'
        },
        context: {
            items: {
                '$ref': '#/components/schemas/Context'
            },
            type: 'array',
            title: 'Context'
        },
        forwardedProps: {
            title: 'Forwardedprops'
        }
    },
    additionalProperties: true,
    type: 'object',
    required: ['threadId', 'runId', 'state', 'messages', 'tools', 'context', 'forwardedProps'],
    title: 'RunAgentInput',
    description: 'Input for running an agent.'
} as const;

export const SystemMessageSchema = {
    properties: {
        id: {
            type: 'string',
            title: 'Id'
        },
        role: {
            type: 'string',
            const: 'system',
            title: 'Role',
            default: 'system'
        },
        content: {
            type: 'string',
            title: 'Content'
        },
        name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        }
    },
    additionalProperties: true,
    type: 'object',
    required: ['id', 'content'],
    title: 'SystemMessage',
    description: 'A system message.'
} as const;

export const TextInputContentSchema = {
    properties: {
        type: {
            type: 'string',
            const: 'text',
            title: 'Type',
            default: 'text'
        },
        text: {
            type: 'string',
            title: 'Text'
        }
    },
    additionalProperties: true,
    type: 'object',
    required: ['text'],
    title: 'TextInputContent',
    description: 'A text fragment in a multimodal user message.'
} as const;

export const ToolSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        },
        description: {
            type: 'string',
            title: 'Description'
        },
        parameters: {
            title: 'Parameters'
        }
    },
    additionalProperties: true,
    type: 'object',
    required: ['name', 'description', 'parameters'],
    title: 'Tool',
    description: 'A tool definition.'
} as const;

export const ToolCallSchema = {
    properties: {
        id: {
            type: 'string',
            title: 'Id'
        },
        type: {
            type: 'string',
            const: 'function',
            title: 'Type',
            default: 'function'
        },
        function: {
            '$ref': '#/components/schemas/FunctionCall'
        }
    },
    additionalProperties: true,
    type: 'object',
    required: ['id', 'function'],
    title: 'ToolCall',
    description: 'A tool call, modelled after OpenAI tool calls.'
} as const;

export const ToolMessageSchema = {
    properties: {
        id: {
            type: 'string',
            title: 'Id'
        },
        role: {
            type: 'string',
            const: 'tool',
            title: 'Role',
            default: 'tool'
        },
        content: {
            type: 'string',
            title: 'Content'
        },
        toolCallId: {
            type: 'string',
            title: 'Toolcallid'
        },
        error: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Error'
        }
    },
    additionalProperties: true,
    type: 'object',
    required: ['id', 'content', 'toolCallId'],
    title: 'ToolMessage',
    description: 'A tool result message.'
} as const;

export const UserMessageSchema = {
    properties: {
        id: {
            type: 'string',
            title: 'Id'
        },
        role: {
            type: 'string',
            const: 'user',
            title: 'Role',
            default: 'user'
        },
        content: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    items: {
                        oneOf: [
                            {
                                '$ref': '#/components/schemas/TextInputContent'
                            },
                            {
                                '$ref': '#/components/schemas/BinaryInputContent'
                            }
                        ],
                        discriminator: {
                            propertyName: 'type',
                            mapping: {
                                binary: '#/components/schemas/BinaryInputContent',
                                text: '#/components/schemas/TextInputContent'
                            }
                        }
                    },
                    type: 'array'
                }
            ],
            title: 'Content'
        },
        name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        }
    },
    additionalProperties: true,
    type: 'object',
    required: ['id', 'content'],
    title: 'UserMessage',
    description: 'A user message supporting text or multimodal content.'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;