// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { AgentAdkEndpointData, AgentAdkEndpointResponse, AgentAgentsStateEndpointData, AgentAgentsStateEndpointResponse, IndicationsListIndicationsResponse, IndicationsGetIndicationData, IndicationsGetIndicationResponse, IndicationsGetDashboardData, IndicationsGetDashboardResponse, UtilsHealthCheckResponse } from './types.gen';

export class AgentService {
    /**
     * Adk Endpoint
     * ADK middleware endpoint.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns unknown Successful Response
     * @throws ApiError
     */
    public static adkEndpoint(data: AgentAdkEndpointData): CancelablePromise<AgentAdkEndpointResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/agent',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Agents State Endpoint
     * EXPERIMENTAL: Retrieve thread state and message history.
     *
     * This endpoint allows front-end frameworks to retrieve the current state
     * and message history for a thread without initiating a new agent run.
     *
     * WARNING: This is an experimental endpoint and is subject to change in
     * future versions. It is provided to support front-end frameworks that
     * require on-demand access to thread state.
     *
     * Args:
     * request_data: Request containing threadId and optional name/properties
     *
     * Returns:
     * JSON response with threadId, threadExists, state, and messages
     * @param data The data for the request.
     * @param data.requestBody
     * @returns unknown Successful Response
     * @throws ApiError
     */
    public static agentsStateEndpoint(data: AgentAgentsStateEndpointData): CancelablePromise<AgentAgentsStateEndpointResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/agent/agents/state',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class IndicationsService {
    /**
     * List Indications
     * List all indications.
     *
     * Returns:
     * All indications with their count.
     * @returns IndicationsPublic Successful Response
     * @throws ApiError
     */
    public static listIndications(): CancelablePromise<IndicationsListIndicationsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/indications/'
        });
    }
    
    /**
     * Get Indication
     * Get a single indication by ID.
     *
     * Args:
     * session: Database session.
     * indication_id: UUID of the indication.
     *
     * Returns:
     * The indication details.
     * @param data The data for the request.
     * @param data.indicationId
     * @returns IndicationPublic Successful Response
     * @throws ApiError
     */
    public static getIndication(data: IndicationsGetIndicationData): CancelablePromise<IndicationsGetIndicationResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/indications/{indication_id}',
            path: {
                indication_id: data.indicationId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Get Dashboard
     * Get the full competitive intelligence dashboard for an indication.
     *
     * Loads all data across all 6 layers in a single request to avoid
     * waterfall requests from the frontend.
     *
     * Args:
     * session: Database session.
     * indication_id: UUID of the indication.
     *
     * Returns:
     * Composite dashboard data spanning all layers.
     * @param data The data for the request.
     * @param data.indicationId
     * @returns DashboardPublic Successful Response
     * @throws ApiError
     */
    public static getDashboard(data: IndicationsGetDashboardData): CancelablePromise<IndicationsGetDashboardResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/indications/{indication_id}/dashboard/',
            path: {
                indication_id: data.indicationId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class UtilsService {
    /**
     * Health Check
     * Health check endpoint.
     * @returns boolean Successful Response
     * @throws ApiError
     */
    public static healthCheck(): CancelablePromise<UtilsHealthCheckResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/utils/health-check/'
        });
    }
}