// This file is auto-generated by @hey-api/openapi-ts

/**
 * An activity progress message emitted between chat messages.
 */
export type ActivityMessage = {
    id: string;
    role?: "activity";
    activityType: string;
    content: {
        [key: string]: unknown;
    };
    [key: string]: unknown | string | "activity";
};

/**
 * Request body for /agents/state endpoint.
 *
 * EXPERIMENTAL: This endpoint is subject to change in future versions.
 */
export type AgentStateRequest = {
    threadId: string;
    appName?: (string | null);
    userId?: (string | null);
    name?: (string | null);
    properties?: (unknown | null);
};

/**
 * An assistant message.
 */
export type AssistantMessage = {
    id: string;
    role?: "assistant";
    content?: (string | null);
    name?: (string | null);
    toolCalls?: (Array<ToolCall> | null);
    [key: string]: unknown | string | "assistant";
};

/**
 * A binary payload reference in a multimodal user message.
 */
export type BinaryInputContent = {
    type?: "binary";
    mimeType: string;
    id?: (string | null);
    url?: (string | null);
    data?: (string | null);
    filename?: (string | null);
    [key: string]: unknown | "binary" | string;
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

/**
 * Additional context for the agent.
 */
export type Context = {
    description: string;
    value: string;
    [key: string]: unknown | string;
};

/**
 * A developer message.
 */
export type DeveloperMessage = {
    id: string;
    role?: "developer";
    content: string;
    name?: (string | null);
    [key: string]: unknown | string | "developer";
};

/**
 * Name and arguments of a function call.
 */
export type FunctionCall = {
    name: string;
    arguments: string;
    [key: string]: unknown | string;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ItemCreate = {
    title: string;
    description?: (string | null);
};

export type ItemPublic = {
    title: string;
    description?: (string | null);
    id: string;
    owner_id: string;
    created_at?: (string | null);
};

export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

/**
 * Input for running an agent.
 */
export type RunAgentInput = {
    threadId: string;
    runId: string;
    parentRunId?: (string | null);
    state: unknown;
    messages: Array<(DeveloperMessage | SystemMessage | AssistantMessage | UserMessage | ToolMessage | ActivityMessage)>;
    tools: Array<Tool>;
    context: Array<Context>;
    forwardedProps: unknown;
    [key: string]: unknown | string | Tool | Context;
};

/**
 * A system message.
 */
export type SystemMessage = {
    id: string;
    role?: "system";
    content: string;
    name?: (string | null);
    [key: string]: unknown | string | "system";
};

/**
 * A text fragment in a multimodal user message.
 */
export type TextInputContent = {
    type?: "text";
    text: string;
    [key: string]: unknown | "text" | string;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

/**
 * A tool definition.
 */
export type Tool = {
    name: string;
    description: string;
    parameters: unknown;
    [key: string]: unknown | string;
};

/**
 * A tool call, modelled after OpenAI tool calls.
 */
export type ToolCall = {
    id: string;
    type?: "function";
    function: FunctionCall;
    [key: string]: unknown | string | "function" | FunctionCall;
};

/**
 * A tool result message.
 */
export type ToolMessage = {
    id: string;
    role?: "tool";
    content: string;
    toolCallId: string;
    error?: (string | null);
    [key: string]: unknown | string | "tool";
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

/**
 * A user message supporting text or multimodal content.
 */
export type UserMessage = {
    id: string;
    role?: "user";
    content: (string | Array<(TextInputContent | BinaryInputContent)>);
    name?: (string | null);
    [key: string]: unknown | string | "user";
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
    created_at?: (string | null);
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type AgentAdkEndpointData = {
    requestBody: RunAgentInput;
};

export type AgentAdkEndpointResponse = (unknown);

export type AgentAgentsStateEndpointData = {
    requestBody: AgentStateRequest;
};

export type AgentAgentsStateEndpointResponse = (unknown);

export type ItemsReadItemsData = {
    limit?: number;
    skip?: number;
};

export type ItemsReadItemsResponse = (ItemsPublic);

export type ItemsCreateItemData = {
    requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = (ItemPublic);

export type ItemsReadItemData = {
    id: string;
};

export type ItemsReadItemResponse = (ItemPublic);

export type ItemsUpdateItemData = {
    id: string;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = (ItemPublic);

export type ItemsDeleteItemData = {
    id: string;
};

export type ItemsDeleteItemResponse = (Message);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);