// This file is auto-generated by @hey-api/openapi-ts

/**
 * An activity progress message emitted between chat messages.
 */
export type ActivityMessage = {
    id: string;
    role?: "activity";
    activityType: string;
    content: {
        [key: string]: unknown;
    };
    [key: string]: unknown | string | "activity";
};

/**
 * Request body for /agents/state endpoint.
 *
 * EXPERIMENTAL: This endpoint is subject to change in future versions.
 */
export type AgentStateRequest = {
    threadId: string;
    appName?: (string | null);
    userId?: (string | null);
    name?: (string | null);
    properties?: (unknown | null);
};

/**
 * An assistant message.
 */
export type AssistantMessage = {
    id: string;
    role?: "assistant";
    content?: (string | null);
    name?: (string | null);
    toolCalls?: (Array<ToolCall> | null);
    [key: string]: unknown | string | "assistant";
};

/**
 * A binary payload reference in a multimodal user message.
 */
export type BinaryInputContent = {
    type?: "binary";
    mimeType: string;
    id?: (string | null);
    url?: (string | null);
    data?: (string | null);
    filename?: (string | null);
    [key: string]: unknown | "binary" | string;
};

/**
 * Additional context for the agent.
 */
export type Context = {
    description: string;
    value: string;
    [key: string]: unknown | string;
};

/**
 * A developer message.
 */
export type DeveloperMessage = {
    id: string;
    role?: "developer";
    content: string;
    name?: (string | null);
    [key: string]: unknown | string | "developer";
};

/**
 * Name and arguments of a function call.
 */
export type FunctionCall = {
    name: string;
    arguments: string;
    [key: string]: unknown | string;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

/**
 * Input for running an agent.
 */
export type RunAgentInput = {
    threadId: string;
    runId: string;
    parentRunId?: (string | null);
    state: unknown;
    messages: Array<(DeveloperMessage | SystemMessage | AssistantMessage | UserMessage | ToolMessage | ActivityMessage)>;
    tools: Array<Tool>;
    context: Array<Context>;
    forwardedProps: unknown;
    [key: string]: unknown | string | Tool | Context;
};

/**
 * A system message.
 */
export type SystemMessage = {
    id: string;
    role?: "system";
    content: string;
    name?: (string | null);
    [key: string]: unknown | string | "system";
};

/**
 * A text fragment in a multimodal user message.
 */
export type TextInputContent = {
    type?: "text";
    text: string;
    [key: string]: unknown | "text" | string;
};

/**
 * A tool definition.
 */
export type Tool = {
    name: string;
    description: string;
    parameters: unknown;
    [key: string]: unknown | string;
};

/**
 * A tool call, modelled after OpenAI tool calls.
 */
export type ToolCall = {
    id: string;
    type?: "function";
    function: FunctionCall;
    [key: string]: unknown | string | "function" | FunctionCall;
};

/**
 * A tool result message.
 */
export type ToolMessage = {
    id: string;
    role?: "tool";
    content: string;
    toolCallId: string;
    error?: (string | null);
    [key: string]: unknown | string | "tool";
};

/**
 * A user message supporting text or multimodal content.
 */
export type UserMessage = {
    id: string;
    role?: "user";
    content: (string | Array<(TextInputContent | BinaryInputContent)>);
    name?: (string | null);
    [key: string]: unknown | string | "user";
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type AgentAdkEndpointData = {
    requestBody: RunAgentInput;
};

export type AgentAdkEndpointResponse = (unknown);

export type AgentAgentsStateEndpointData = {
    requestBody: AgentStateRequest;
};

export type AgentAgentsStateEndpointResponse = (unknown);

export type UtilsHealthCheckResponse = (boolean);