"""initial_market_analysis_models

Revision ID: 9d979e06033f
Revises: 
Create Date: 2026-02-21 19:52:55.845773

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '9d979e06033f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('indication',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('icd_code', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('market_size_usd_bn', sa.Float(), nullable=True),
    sa.Column('market_growth_pct', sa.Float(), nullable=True),
    sa.Column('market_year', sa.Integer(), nullable=True),
    sa.Column('market_history', sa.JSON(), nullable=True),
    sa.Column('market_years', sa.JSON(), nullable=True),
    sa.Column('projected_size_usd_bn', sa.Float(), nullable=True),
    sa.Column('projected_year', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cagr_pct', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('pipeline_phase1', sa.Integer(), nullable=False),
    sa.Column('pipeline_phase2', sa.Integer(), nullable=False),
    sa.Column('pipeline_phase3', sa.Integer(), nullable=False),
    sa.Column('pipeline_filed', sa.Integer(), nullable=False),
    sa.Column('pipeline_marketed', sa.Integer(), nullable=False),
    sa.Column('pipeline_total', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_indication_name'), 'indication', ['name'], unique=False)
    op.create_table('aiassessment',
    sa.Column('layer', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('indication_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['indication_id'], ['indication.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comparabletransaction',
    sa.Column('date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('transaction_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('parties', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('asset', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('total_value', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('upfront_value', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('indication_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['indication_id'], ['indication.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('compound',
    sa.Column('brand_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('inn', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('sponsor', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('moa', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('phase', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('route', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('frequency', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('primary_efficacy_measure', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('primary_efficacy_value', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('onset_of_action', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('safety_profile', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('has_black_box_warning', sa.Boolean(), nullable=False),
    sa.Column('regulatory_designations', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('approval_year', sa.Integer(), nullable=True),
    sa.Column('indication_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['indication_id'], ['indication.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('expansionindication',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('market_size_usd_bn', sa.Float(), nullable=True),
    sa.Column('patient_population', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('competitive_density', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('validation_status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('scientific_rationale', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('indication_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['indication_id'], ['indication.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gonogocriterion',
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_met', sa.Boolean(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('indication_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['indication_id'], ['indication.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patientpopulation',
    sa.Column('total_prevalence', sa.Float(), nullable=False),
    sa.Column('diagnosed', sa.Float(), nullable=False),
    sa.Column('treatable', sa.Float(), nullable=False),
    sa.Column('treated', sa.Float(), nullable=False),
    sa.Column('unit', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('indication_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['indication_id'], ['indication.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('standardofcare',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('line_of_therapy', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('limitation', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('indication_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['indication_id'], ['indication.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('target',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('target_class', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('most_advanced_phase', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('has_marketed_drug', sa.Boolean(), nullable=False),
    sa.Column('crowding', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('compound_count', sa.Integer(), nullable=False),
    sa.Column('indication_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['indication_id'], ['indication.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('thesisrisk',
    sa.Column('risk', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('detail', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('severity', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('indication_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['indication_id'], ['indication.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('unmetneed',
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('indication_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['indication_id'], ['indication.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('compoundtarget',
    sa.Column('compound_id', sa.Uuid(), nullable=False),
    sa.Column('target_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['compound_id'], ['compound.id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['target.id'], ),
    sa.PrimaryKeyConstraint('compound_id', 'target_id')
    )
    op.create_table('marketeddrugdata',
    sa.Column('revenue_history_m', sa.JSON(), nullable=True),
    sa.Column('revenue_years', sa.JSON(), nullable=True),
    sa.Column('market_share_pct', sa.Float(), nullable=True),
    sa.Column('share_change_pct', sa.Float(), nullable=True),
    sa.Column('wac_price_usd', sa.Float(), nullable=True),
    sa.Column('formulary_access_pct', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('nbrx_volume', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('nbrx_trend', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('has_post_market_safety_flag', sa.Boolean(), nullable=False),
    sa.Column('safety_flag_detail', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('compound_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['compound_id'], ['compound.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('compound_id')
    )
    op.create_table('trial',
    sa.Column('trial_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('phase', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('target_enrollment', sa.Integer(), nullable=True),
    sa.Column('current_enrollment_pct', sa.Float(), nullable=True),
    sa.Column('enrollment_velocity', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('primary_completion_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('primary_endpoint', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('endpoint_timepoint', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('comparator', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('compound_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['compound_id'], ['compound.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trial')
    op.drop_table('marketeddrugdata')
    op.drop_table('compoundtarget')
    op.drop_table('unmetneed')
    op.drop_table('thesisrisk')
    op.drop_table('target')
    op.drop_table('standardofcare')
    op.drop_table('patientpopulation')
    op.drop_table('gonogocriterion')
    op.drop_table('expansionindication')
    op.drop_table('compound')
    op.drop_table('comparabletransaction')
    op.drop_table('aiassessment')
    op.drop_index(op.f('ix_indication_name'), table_name='indication')
    op.drop_table('indication')
    # ### end Alembic commands ###
