"""drop target crowding and compound_count columns

Revision ID: c7a57651741e
Revises: 9d979e06033f
Create Date: 2026-02-22 20:42:43.773943

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'c7a57651741e'
down_revision = '9d979e06033f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('target', 'compound_count')
    op.drop_column('target', 'crowding')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('target', sa.Column('crowding', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
    op.add_column('target', sa.Column('compound_count', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
